#!/usr/bin/env python
import rospy
from servosix import ServoSix
import time

def callback(data):
    #move gripper to requested position
    while True:
	    ss.set_servo(1,data.data)

    
def listener():
    rospy.init_node('gripperControl', anonymous=True)
    rospy.Subscriber("gripperControl", int, callback)
    rospy.spin()

if __name__ == '__main__':
    ss= ServoSix()
    listener()