#!/usr/bin/env python
import rospy
from servosix import ServoSix
from std_msgs.msg import Int32
import time

def callback(data):
    # move gripper to requested position
    ss.set_servo(1,data.data)
    ss.cleanup()

    
def listener():
    rospy.init_node('gripperControl', anonymous=True)
    rospy.Subscriber("gripperControl", Int32, callback)
    rospy.spin()

if __name__ == '__main__':
    ss= ServoSix()
    listener()