#!/usr/bin/env python

import sys
import time
import rospy

from std_msgs.msg import String
from std_msgs.msg import Int32

if __name__=='__main__':
    try:
        #setup publisher to send gripper commands
        pubGripper = rospy.Publisher('/gripperControl',Int32, queue_size=1)
        time.sleep(.5) 
        pubGripper.publish(sys.argv[1])  

    except rospy.ROSInterruptException:
        pass
