#!/usr/bin/env python
import rospy
import RPi.GPIO as GPIO
from std_msgs.msg import Int32
import time

def callback(data):
    if data.data == 0:
        # turn mixer off
        GPIO.output(26,0)
        print("turning mixer off")
    elif data.data == 1:
        # turn mixer on
        GPIO.output(26,1)
        print("turning mixer on")
    
def listener():
    rospy.init_node('mixerControl', anonymous=True)
    rospy.Subscriber("mixerControl", Int32, callback)
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(26,GPIO.OUT)
    rospy.spin()

if __name__ == '__main__':
    listener()