#!/usr/bin/env python

import sys
import time
import rospy

from std_msgs.msg import String
from std_msgs.msg import Int32

if __name__=='__main__':
    try:
        #create the ROS node for the application	
        rospy.init_node('mixer_command')
        
        #setup publisher to send mixer commands
        pubMixer = rospy.Publisher('/mixerControl',Int32, queue_size=1)
        time.sleep(1) 
        if sys.argv[1] == "ON": 
            pubMixer.publish(1) 
        elif sys.argv[1] == "OFF": 
            pubMixer.publish(0)  
        else:
            print("invalid command")
    except rospy.ROSInterruptException:
        pass
