#!/usr/bin/env python
import rospy
from std_msgs.msg import Int32
import time

def callback(data):
    if data.data == 0:
        # turn mixer off
        print("turning mixer off")
    else if data.data == 1:
        # turn mixer on
        print("turning mixer on")
    
def listener():
    rospy.init_node('mixerControl', anonymous=True)
    rospy.Subscriber("mixerControl", Int32, callback)
    rospy.spin()

if __name__ == '__main__':
    listener()