#!/usr/bin/env python

#This is the file to make my first  shake
#a proof of concept with only protein and water
#testing github

import rospy
import time
from std_msgs.msg import String
from shakestation.msg import JointPose

def build_shake():
	#create the ROS node for the application	
	rospy.init_node('shakemaker')

	#move the manipulator to the initial pose
	pub2 = rospy.Publisher('/robotis/base/joint_pose_msg',JointPose, queue_size=1)
	msg2 = "<add the inital message here>"
	time.sleep(.2)
	pub2.publish(msg2)
	print("moved to first pose")


if __name__=='__main__':
	try:
		build_shake()
	except rospy.ROSInterruptException:
		pass
