#!/usr/bin/env python

import sys
import time
import rospy

from std_msgs.msg import Int32

if __name__=='__main__':
    try:
        #create the ROS node for the application	
        rospy.init_node('water_valve_command')
        
        #setup publisher to send mixer commands
        pubWaterValve = rospy.Publisher('/waterValveControl',Int32, queue_size=1)
        time.sleep(.1) 
        if int(sys.argv[1]) == 1: 
            pubWaterValve.publish(1) 
        elif int(sys.argv[1]) == 0: 
            pubWaterValve.publish(0)  
        else:
            print("invalid command")
    except rospy.ROSInterruptException:
        pass