#!/usr/bin/env python
import rospy
import RPi.GPIO as GPIO
from std_msgs.msg import Int32
import time

def callback(data):
    if data.data == 0:
        # close water valve
        GPIO.output(21,0)
        print("opening water valve")
    elif data.data == 1:
        # open water valve
        GPIO.output(21,1)
        print("closing water valve")
    
def listener():
    rospy.init_node('waterValveControl', anonymous=True)
    rospy.Subscriber("waterValveControl", Int32, callback)
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(21,GPIO.OUT)
    rospy.spin()

if __name__ == '__main__':
    listener()